export default [
	'<span data-filter="player" data-value="Stephen Curry" class="description__link">Stephen Curry</span> has the 21 of the top 100 moments from this season. But #1 moment belongs to <span data-filter="play" data-value="Pan_1zX0RPE" class="description__link">Devin Booker&rsquo;s 70 point game</span>, viewed over 4 million times. <span data-filter="player" data-value="Russell Westbrook" class="description__link">Russell Westbrook</span> has #2, when he notched his <span data-filter="play" data-value="sLwLoicdKsI" class="description__link">42nd triple-double</span>. Also noteworthy: <span data-filter="play" data-value="1SmSVTSgvc4"  class="description__link">Pierce’s farewell 3 in Boston</span> and <span data-filter="play" data-value="zHLaT0mfoBY"  class="description__link">Durant and Westbrook meet for the first time</span>.',

	'<span data-filter="player" data-value="Kobe" class="description__link">Kobe</span> leads the 2010s, with 14M views for his <span data-filter="play" data-value="YFSSaLB-4SA" class="description__link">final NBA game</span>. It’s only slightly higher than one of the most-viewed game-winners on YouTube: <span data-filter="play" data-filter="play" data-value="lz29FUCJWWc" data-value="lz29FUCJWWc" class="description__link">Curry’s last shot vs. Thunder</span> on February 27, 2016, a regular season game! Also noteworthy: <span data-filter="play" data-value="0-yh0hf7sBU"  class="description__link">Game 7 of the 2016 Finals</span> and <span data-filter="play" data-value="tr6XsZVb-ZE" class="description__link">Ray Allen ties Game 6 of the 2013 Finals</span>.',

	'<span data-filter="play" data-value="ceLlz7dOOvY" class="description__link">Tracy McGrady’s 13 points in 33 seconds</span> is the 2nd most-viewed moment in NBA history, with 27 million views. The 2010s also include the 3rd most-viewed moment: <span data-filter="play" data-value="FeXZY4eVLlo" class="description__link">Kobe’s 81 point game</span>. Also noteworthy: <span data-filter="play" data-value="NSnAvhvfniw" class="description__link">Derek Fisher’s 0.4 second game-winner</span>, <span data-filter="play" data-value="grXws5m11SA" class="description__link">Iverson steps over Lue</span>, <span data-filter="play" data-value="Ff9n_5oayuQ" class="description__link">Jordan’s final game</span>, and <span data-filter="play" data-value="ACZnF87Iy84" class="description__link">Kobe’s game-winner vs. Suns, Playoffs 2006</span>.',

	'<span data-filter="play" data-value="530z-_yjdlU" class="description__link">Jordan’s last 3 minutes as Bull</span> is the most-viewed moment in NBA history, with 35 million views. <span data-filter="player" data-value="Jordan" class="description__link">Jordan</span> has 65 of the top 100 from the 1990s, including his <span data-filter="play" data-value="YIzrYcgfOH4" class="description__link">“Flu Game”</span>. Also noteworthy: <span data-filter="play" data-value="aSWE_Wbu80o" class="description__link">Reggie Miller&rdquo;s 8 points in 9 seconds</span>.',

	'The 1980s includes moments from a number of hall of famers, including <span data-filter="player" data-value="Michael Jordan" class="description__link">Jordan</span>, <span data-filter="player" data-value="larry bird" class="description__link">Bird</span>, <span data-filter="player" data-value="magic johnson" class="description__link">Magic</span>, and <span data-filter="player" data-value="julius erving" class="description__link">Julius Erving</span>. Notable moments include <span data-filter="play" data-value="p5WUOnTxwPw" class="description__link">“The Shot”</span>, <span data-filter="play" data-value="H_RJ5XN8TK8" class="description__link">Bird steals inbound for game winner</span>, <span data-filter="play" data-value="f7njB1T-Xjk" class="description__link">Dr. J’s baseline layup</span>, and <span data-filter="play" data-value="2fySp51bhsQ" class="description__link">“The Hook Shot”</span>.',
]
